openapi: 3.0.1
info:
  title: drgsubReleaseApi
  description: API Definition of drgsubReleaseApi
  version: 1.0.0
servers:
- url: http://localhost:8290/drgsubreleaseapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
